### PR TITLE
Suggested revision

### PR DESCRIPTION
**Pull request by ptr2019**
After going through the whole file, I suggest some revises, e.g.,

>backup_download_tooltip: "下载应用程序的所有数据，又名主题、歌曲、文件夹"
changes into
>backup_download_tooltip: "下载应用程序的所有数据，即主题、歌曲、文件夹"
where "aka"/also known as, could be interpreted as "即“ which indicates detailed explanation/list, rather than "又名" which literally means ”I am going to introduce another name for it“.

> delete_songs_and_folders_tooltip: "在这里您可以删除所有主题"
changes into
> delete_songs_and_folders_tooltip: "在这里您可以删除所有歌曲和文件夹"
where "songs" is ”歌曲“ while ”主题“ means ”theme“.

Other changes are mostly adding missing periods for complete sentences, where periods (or question marks) already appears in the middle and maybe it is better to end the last sentence with a period. Those may not be a big deal, though.

When to merge is up to the release plan.

### CODE REVIEW

**Comment by Specy** [comment]
Sure! I'll merge this, I was thinking of publishing the new version tomorrow, do you think the translation is good enough to be released for now?

**Comment by ptr2019** [comment]
I think it's okay for what I have seen. 

I haven't checked some of the "hidden" descriptions, prompts, or messages in the web app. I am not sure if they are correct or appropriate for their context without viewing them "at live". 

Further exploration may be conducted, and I will update as soon as there are some findings.

**Comment by Specy** [comment]
Not sure if you saw but those changes are published in the beta here:
https://beta.sky-music.specy.app/
I'll merge those in the meanwhile

**Comment by ptr2019** [comment]
Yeah I am checking this demo, also the https://beta.genshin-music.specy.app/ to see if everything goes well.

**Comment by Specy** [comment]
Yes, It's a minor detail but would be really annoying to implement, I need to change how the settings work to add it, I don't have time to work on that now. After releasing the new version I'll have to work on adding sustained instruments, which will be hard and take a long time to add, and I'm not sure I can work on it yet

**Pull request merged**
