### PR TITLE
Add translation

### PR DESCRIPTION
**Pull request by ptr2019**
Current Chinese Translation proposed. To be revised following further implementations, user experiences, and feedback.

### CODE REVIEW

**Comment by Specy** [comment]
@cangerjun what do you think?

**Comment by cangerjun** [comment]
> @cangerjun what do you think

Obviously, his translation is better than mine. I think we should all merge him.^_^

**Comment by Specy** [comment]
Ok thank you, i'll merge this and fix the issues, then we can start testing on the beta of the app.

I'm also going to publish an announcement on my discord server to look for more translators for other languages

**Comment by Specy** [comment]
@ptr2019 I've fixed the errors in the file, can you check if the changed lines are still correct? for example i think "songs" and "themes" that were translated aren't in plural
Look at the commit here: https://github.com/Specy/genshin-music/commit/98c044c592467d549f0ec35ad9ce272f7773fd13

**Comment by ptr2019** [comment]
> @ptr2019 I've fixed the errors in the file, can you check if the changed lines are still correct? for example i think "songs" and "themes" that were translated aren't in plural Look at the commit here: [98c044c](https://github.com/Specy/genshin-music/commit/98c044c592467d549f0ec35ad9ce272f7773fd13)

Got it.

**Comment by ptr2019** [comment]
> @ptr2019 I've fixed the errors in the file, can you check if the changed lines are still correct? for example i think "songs" and "themes" that were translated aren't in plural Look at the commit here: [98c044c](https://github.com/Specy/genshin-music/commit/98c044c592467d549f0ec35ad9ce272f7773fd13)

Yes, the errors have been fixed and now things are in the right way. Sorry for the inconvenience. Look forward to more new features, e.g., the Nightwind horn. >v<

**Pull request merged**
