### PR TITLE
Switched to yarn and fixed 10 eslint errors

### PR DESCRIPTION
**Pull request by tnb24**
yarn has consistently been proven to be faster than npm and code without warnings just look better :)

### CODE REVIEW

**Comment by tnb24** [comment]
also removed testing libraries as no tests were provided

**Comment by Specy** [comment]
in the `scripts` folder there are two scripts which still rely on npm

**Comment by tnb24** [comment]
fixed it @Specy

**Comment by Specy** [comment]
the lack of space in `{chosenApp}&&` was intentional, else the env variable will have a space in it.

That affects both scripts

**Comment by tnb24** [comment]
oh lol gimme a sec

**Comment by tnb24** [comment]
fixed

**Pull request merged**
