### PR TITLE
Adding Indonesian Translate

### PR DESCRIPTION
**Pull request by GID0317**

### CODE REVIEW

**Comment by Specy** [comment]
I'm gonna add this to beta first to test things out properly, it will be available at https://beta.sky-music.specy.app/ and https://beta.genshin-music.specy.app/

**Comment by Specy** [comment]
Ok @GID0317 I've published the branch to BETA, could you try it out to make sure the translation fits the app?
https://beta.sky-music.specy.app/ 
https://beta.genshin-music.specy.app/

**Comment by Specy** [comment]
I've published this live in the meanwhile, thank you for the PR!

**Comment by Specy** [comment]
I'm gonna delay this to the next version as it's a minor change

**Comment by Specy** [comment]
Sorry for rushing the PR but there was a bug fix I wanted to merge today

**Comment by GID0317** [comment]
I see, no problem!

**Pull request merged**
