### PR TITLE
Translation added

### PR DESCRIPTION
**Pull request by ptr2019**
Translation is added for the theme setting and instruments, etc., and revises are made for several terms previously translated, based on personal experience after several days of usage.

### CODE REVIEW

**Comment by Specy** [comment]
@cangerjun what do you think?

**Comment by ptr2019** [comment]
Admittedly I am not quite sure about the name of several instruments from the game Sky, which I am not quite familiar with, such as the light guitar (which sounds weak and light, seemingly with light string), and some of the sound effects, e.g., is the "bird call" simply "鸟叫" in the game, or their is another official name for it.

**Comment by Specy** [comment]
> Admittedly I am not quite sure about the names of several instruments from the game Sky, which I am not familiar with, such as the light guitar (which sounds weak and light, seemingly with light string), and some of the sound effects, e.g., is the "bird call" simply "鸟叫" in the game, or another official name.

I'm gonna ask for some people who use the app to review the translation, also the "call" is the sound that animals make to "attract" other animals, like "a bird calling another bird"

**Comment by ptr2019** [comment]
Sound for "attraction", aha, got it. Further review is also needed indeed. I have just found that in this game, the manta has its Chinese name as "遥鲲" and spirit manta is "透明遥鲲"...

**Comment by Specy** [comment]
should i merge this in the meanwhile? or are you still working on it

**Comment by ptr2019** [comment]
Both merge or not are okay for me. I have already finished my part↓

> Admittedly I am not quite sure about the names of several instruments from the game Sky, which I am not familiar with, such as the light guitar (which sounds weak and light, seemingly with light string), and some of the sound effects, e.g., is the "bird call" simply "鸟叫" in the game, or another official name.

The rest is left to community feedback↓

> > Admittedly I am not quite sure about the names of several instruments from the game Sky, which I am not familiar with, such as the light guitar (which sounds weak and light, seemingly with light string), and some of the sound effects, e.g., is the "bird call" simply "鸟叫" in the game, or another official name.
> 
> I'm gonna ask for some people who use the app to review the translation, also the "call" is the sound that animals make to "attract" other animals, like "a bird calling another bird"

**Comment by Specy** [comment]
i'll see if i can find chinese speaking people who can give a review to this

**Comment by ptr2019** [comment]
Sorry for closing the PR too soon >v<
 It seems that the merge has not been done yet. I will just leave it here, then.

**Comment by Specy** [comment]
I'm gonna answer back here instead of the issue but, there is 
```
        midi_status: "MIDI status",
        midi_access_denied: "MIDI access was denied, please allow it in the browser settings and reload the page",
        midi_access_unsupported: "MIDI is not supported in this browser",
        midi_access_pending: "Waiting for MIDI access...",
        midi_access_granted: "MIDI available!",
```
that need translation.

I'm sorry for asking so many times to add translations, but i keep on adding things as i find/add new features xD

**Comment by ptr2019** [comment]
> I'm gonna answer back here instead of the issue but, there is
> 
> ```
>         midi_status: "MIDI status",
>         midi_access_denied: "MIDI access was denied, please allow it in the browser settings and reload the page",
>         midi_access_unsupported: "MIDI is not supported in this browser",
>         midi_access_pending: "Waiting for MIDI access...",
>         midi_access_granted: "MIDI available!",
>         
>         new: "New",
> ```
> 
> that need translation.
> 
> I'm sorry for asking so many times to add translations, but i keep on adding things as i find/add new features xD

Sure. Looking on it, awa.

**Pull request merged**
